// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MumbleDB.Data;

#nullable disable

namespace MumbleDB.Data.Migrations
{
    [DbContext(typeof(MumbleDBContext))]
    [Migration("20240418122114_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MumbleDB.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("FromUserID");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Message");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int")
                        .HasColumnName("ToUserID");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C0C9C2E13BC06");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MumbleDB.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C4F8167F5");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MumbleDB.Models.Message", b =>
                {
                    b.HasOne("MumbleDB.Models.User", "FromUser")
                        .WithMany("MessageFromUsers")
                        .HasForeignKey("FromUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__FromUs__628FA481");

                    b.HasOne("MumbleDB.Models.User", "ToUser")
                        .WithMany("MessageToUsers")
                        .HasForeignKey("ToUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__ToUser__6383C8BA");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("MumbleDB.Models.User", b =>
                {
                    b.Navigation("MessageFromUsers");

                    b.Navigation("MessageToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
